export const FETCH_ITEM_DETAILS_REQUEST = 'FETCH_ITEM_DETAILS_REQUEST'
export const FETCH_ITEM_DETAILS_SUCCESS = 'FETCH_ITEM_DETAILS_SUCCESS'
export const FETCH_ITEM_DETAILS_FAIL = 'FETCH_ITEM_DETAILS_FAIL'
